CREATE TABLE tenant_feature_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    feature_id BIGINT NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    reason VARCHAR(500),
    granted_by VARCHAR(100),
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tenant_feature UNIQUE (tenant_id, feature_id)
);
