ALTER TABLE employee_documents ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE employee_documents ADD COLUMN IF NOT EXISTS verified_by VARCHAR(255);
ALTER TABLE employee_documents ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;
