'use client';

import React from 'react';

interface AiDisclaimerProps {
  level: 'advisory' | 'high-risk';
  compact?: boolean;
  provider?: string;
  model?: string;
}

export default function AiDisclaimer({ level, compact = false, provider, model }: AiDisclaimerProps) {
  const messages = {
    advisory: 'AI-assisted suggestion. Review before use.',
    'high-risk': 'AI-assisted analysis. This should inform, not replace, human judgment.',
  };

  return (
    <div className={`flex items-start gap-2 ${compact ? 'py-1.5 px-2' : 'py-2 px-3'} bg-gray-50 border border-gray-200 rounded-md`}>
      <svg className="w-3.5 h-3.5 text-gray-400 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
      </svg>
      <div className="flex-1 min-w-0">
        <p className={`${compact ? 'text-[10px]' : 'text-xs'} text-gray-500 leading-tight`}>
          {messages[level]}
        </p>
        {provider && model && (
          <p className={`${compact ? 'text-[9px]' : 'text-[10px]'} text-gray-400 mt-0.5`}>
            Generated by {provider} · {model}
          </p>
        )}
      </div>
    </div>
  );
}
