name: Deploy to Pre-Production

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ppe
      aws-region: af-south-1
      domain-name: shumelahire.co.za
      hosted-zone-name: ppe.shumelahire.co.za
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      API_CERTIFICATE_ARN: ${{ secrets.API_CERTIFICATE_ARN }}
      WILDCARD_CERTIFICATE_ARN: ${{ secrets.WILDCARD_CERTIFICATE_ARN }}
      LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
      LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
