name: Deploy to Dev

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      aws-region: af-south-1
      domain-name: shumelahire.co.za
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      API_CERTIFICATE_ARN: ${{ secrets.API_CERTIFICATE_ARN }}
      WILDCARD_CERTIFICATE_ARN: ${{ secrets.WILDCARD_CERTIFICATE_ARN }}
